[[language]]
name = "rust"

[language-server.rust-analyzer.config]
rust-analyzer.checkOnSave.allTargets = false
# rust-analyzer.checkOnSave.extraArgs = ["--bins"]

# rust-analyzer.linkedProjects = [ "./board/Cargo.toml", "./Cargo.toml" ]
